# Habit Reminder RL Configuration

environment:
  max_reminders_per_day: 3
  hours_in_day: 24
  simulation_days: 90
  
agent:
  state_dim: 15  # Will be computed from environment
  action_dim: 5  # [send_now, wait_30m, wait_1h, wait_2h, skip_today]
  hidden_dims: [128, 64, 32]
  learning_rate: 0.001
  gamma: 0.95  # Discount factor
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 0.995
  batch_size: 64
  memory_size: 10000
  target_update_freq: 100  # Update target network every N steps
  
training:
  num_episodes: 500
  max_steps_per_episode: 100
  save_freq: 50  # Save model every N episodes
  eval_freq: 10  # Evaluate every N episodes
  eval_episodes: 10
  
rewards:
  completion_immediate: 15.0  # Completed within 30 min
  completion_soon: 12.0       # Completed within 2 hours
  completion_later: 8.0       # Completed same day
  ignored: -1.0
  dismissed: -3.0
  snoozed: -0.5
  spam_penalty: -2.0          # Too many ignored reminders
  streak_bonus: 3.0           # Maintaining streaks
  efficiency_bonus: 1.0       # Not spamming
  
user_profiles:
  # Different user types for simulation
  morning_person:
    preferred_hours: [6, 7, 8, 9]
    completion_prob: 0.8
    
  evening_person:
    preferred_hours: [18, 19, 20, 21]
    completion_prob: 0.8
    
  weekend_warrior:
    preferred_hours: [10, 11, 12]
    completion_prob: 0.9
    weekend_boost: 0.2
    
  inconsistent:
    preferred_hours: [12, 13, 14, 15, 16, 17, 18]
    completion_prob: 0.5

